-- ============================================================
-- Blog Seed Script — Mind Motion Matrix (Dr. Kirthi)
-- Run this in Supabase Dashboard -> SQL Editor -> New query -> Run
-- Safe to re-run: uses ON CONFLICT so it won't duplicate.
-- All posts are fully editable later from /admin/posts in your site.
-- ============================================================

-- 1) Categories (varied types incl. trending + issue-based)
insert into blog_categories (name, slug) values
  ('Mental Health', 'mental-health'),
  ('Homeopathy', 'homeopathy'),
  ('Anxiety & Stress', 'anxiety-stress'),
  ('Parenting & Child Care', 'parenting'),
  ('Relationships', 'relationships'),
  ('Trending', 'trending'),
  ('Common Issues', 'common-issues')
on conflict (slug) do nothing;

-- 2) Blog Posts (15)
insert into blog_posts (title, slug, excerpt, content, cover_image, category, published, published_at) values

('Understanding Anxiety: Signs, Causes, and the Homeopathic Approach',
'understanding-anxiety-signs-causes-homeopathic-approach',
'Anxiety is one of the most common mental health concerns today. Learn to recognise the early signs and how homeopathy offers a gentle, root-cause approach to relief.',
'<h2>What Is Anxiety?</h2><p>Anxiety is the body''s natural response to stress, but when worry becomes constant and starts affecting daily life, it may point to an anxiety disorder. Millions of people across India silently struggle with racing thoughts, restlessness, and a persistent sense of unease.</p><h2>Common Signs to Watch For</h2><ul><li>Constant overthinking or catastrophic thinking</li><li>Rapid heartbeat, sweating, or shortness of breath</li><li>Difficulty concentrating or sleeping</li><li>Irritability and muscle tension</li><li>Avoidance of social or work situations</li></ul><h2>Why Anxiety Happens</h2><p>Anxiety can stem from genetic predisposition, prolonged stress, unresolved trauma, hormonal imbalance, or lifestyle factors such as poor sleep and excessive screen time. Often it is not one cause but a combination of triggers building up over time.</p><h2>The Homeopathic Approach</h2><p>Homeopathy treats anxiety by looking at the person as a whole — their emotional history, personality, and physical symptoms together — rather than only suppressing the worry. Remedies are selected individually, aiming to gently restore the nervous system''s natural balance without the dependency risks associated with some conventional medications.</p><h2>When to Seek Help</h2><p>If anxiety is interfering with your relationships, work, or sleep, it is time to consult a qualified professional. Early intervention leads to much smoother recovery.</p>',
'https://picsum.photos/seed/anxiety-signs/900/600',
'anxiety-stress', true, now() - interval '28 days'),

('How Homeopathy Treats Chronic Depression Naturally',
'how-homeopathy-treats-chronic-depression-naturally',
'Depression is more than sadness — it is a persistent state that affects thought, energy, and motivation. Discover how a constitutional homeopathic approach supports long-term emotional recovery.',
'<h2>Depression Is Not Just "Feeling Low"</h2><p>Chronic depression involves a prolonged loss of interest, low energy, disturbed sleep, and a sense of hopelessness that does not resolve on its own. It affects people of every age group, though it often goes unspoken due to stigma.</p><h2>Root Causes</h2><p>Depression may arise from biochemical imbalances, unresolved grief, chronic stress, hormonal changes, or a genetic predisposition. In many cases, it develops slowly and is dismissed as "just a phase" until it becomes overwhelming.</p><h2>A Constitutional Approach</h2><p>Unlike a one-size-fits-all remedy, homeopathic treatment for depression is individualised — it considers a person''s emotional triggers, physical constitution, sleep pattern, and personal history. This whole-person method aims to address the underlying imbalance rather than only masking symptoms.</p><h2>Lifestyle Support Alongside Treatment</h2><ul><li>Regular sunlight exposure and movement</li><li>Consistent sleep-wake schedule</li><li>Reducing isolation through supportive relationships</li><li>Mindful reduction of stimulant intake (caffeine, screens before bed)</li></ul><h2>Recovery Is Gradual and Real</h2><p>With consistent, individualised care, many patients experience a steady return of energy, motivation, and emotional stability. If you or a loved one is struggling, reaching out for professional support is the most important first step.</p>',
'https://picsum.photos/seed/depression-care/900/600',
'homeopathy', true, now() - interval '26 days'),

('5 Early Signs of Stress You Should Not Ignore',
'5-early-signs-of-stress-you-should-not-ignore',
'Stress often builds quietly before it becomes overwhelming. Here are five early warning signs your body and mind may be sending you.',
'<h2>Why Early Detection Matters</h2><p>Chronic, unmanaged stress is linked to anxiety, poor sleep, digestive issues, and weakened immunity. Recognising it early makes it far easier to manage before it escalates.</p><h2>1. Persistent Fatigue</h2><p>Feeling tired even after a full night''s sleep is often one of the first signs the body is running on stress hormones like cortisol for too long.</p><h2>2. Irritability Over Small Things</h2><p>When minor inconveniences start triggering disproportionate frustration, it usually signals an overloaded nervous system.</p><h2>3. Changes in Appetite</h2><p>Stress can suppress or increase appetite, often leading to skipped meals or emotional eating.</p><h2>4. Difficulty Sleeping</h2><p>Racing thoughts at bedtime, frequent waking, or restless sleep are classic early indicators of accumulated stress.</p><h2>5. Physical Tension</h2><p>Unexplained headaches, jaw clenching, or tight shoulders are the body''s physical response to prolonged mental strain.</p><h2>What You Can Do</h2><p>Simple daily practices — short walks, deep breathing, digital detox time, and speaking to someone you trust — can meaningfully reduce stress levels. If these signs persist for weeks, consider professional support.</p>',
'https://picsum.photos/seed/stress-signs/900/600',
'mental-health', true, now() - interval '24 days'),

('Parenting a Child with ADHD: A Homeopathic Perspective',
'parenting-child-with-adhd-homeopathic-perspective',
'Raising a child with ADHD comes with unique challenges. Here is how parents can create a supportive environment while exploring gentle, individualised homeopathic care.',
'<h2>Understanding ADHD in Children</h2><p>Attention-Deficit/Hyperactivity Disorder affects a child''s ability to focus, sit still, and regulate impulses. It is not a result of poor parenting — it is a neurodevelopmental pattern that benefits from structured support and patience.</p><h2>Common Signs Parents Notice</h2><ul><li>Difficulty completing tasks or homework</li><li>Constant fidgeting or restlessness</li><li>Interrupting conversations or struggling to wait turns</li><li>Emotional outbursts that seem sudden and intense</li></ul><h2>Creating a Supportive Home Environment</h2><p>Consistent routines, clear and simple instructions, positive reinforcement, and adequate physical activity can significantly help children manage their symptoms day to day.</p><h2>The Role of Homeopathy</h2><p>Homeopathic treatment for ADHD focuses on the child''s individual temperament, sleep pattern, and behavioural triggers, aiming to support calmer focus and emotional regulation gently, without the sedative effects some parents worry about with conventional options.</p><h2>Working With Professionals</h2><p>A collaborative approach involving parents, teachers, and your treating doctor gives children with ADHD the best chance to thrive both academically and emotionally.</p>',
'https://picsum.photos/seed/adhd-parenting/900/600',
'parenting', true, now() - interval '22 days'),

('Why Mental Health Awareness Matters in India Today',
'why-mental-health-awareness-matters-in-india-today',
'India is having an important, overdue conversation about mental health. Here is why awareness — not just treatment — is the real turning point.',
'<h2>A Growing but Silent Crisis</h2><p>Surveys consistently show a significant proportion of Indians experience mental health concerns at some point, yet a majority never seek professional help due to stigma, lack of awareness, or limited access.</p><h2>The Stigma Problem</h2><p>Mental health struggles are often dismissed as "weakness" or hidden from family and colleagues. This silence delays treatment and worsens outcomes for people who could otherwise recover well with timely care.</p><h2>Why Awareness Is the First Step</h2><p>When people understand that anxiety, depression, and burnout are medical conditions — not character flaws — they become more willing to seek support early, exactly when treatment is most effective.</p><h2>Encouraging Change</h2><ul><li>Workplaces introducing mental health days and counselling access</li><li>Schools starting emotional wellness programs</li><li>Public figures speaking openly about their own struggles</li><li>Growing acceptance of therapy and holistic treatment options</li></ul><h2>What You Can Do</h2><p>Start conversations, check in on people around you, and normalise seeking help. Awareness saves lives — and it starts with each of us.</p>',
'https://picsum.photos/seed/mental-health-india/900/600',
'trending', true, now() - interval '20 days'),

('Common Sleep Disorders and How Homeopathy Can Help',
'common-sleep-disorders-how-homeopathy-can-help',
'From insomnia to restless sleep, disturbed sleep affects millions. Explore common sleep issues and a gentle, natural path back to restorative rest.',
'<h2>Why Sleep Matters So Much</h2><p>Sleep is when the brain consolidates memory, regulates emotion, and the body repairs itself. Chronic poor sleep is linked to anxiety, weight gain, weakened immunity, and reduced concentration.</p><h2>Common Sleep Disorders</h2><ul><li><strong>Insomnia:</strong> difficulty falling or staying asleep</li><li><strong>Restless sleep:</strong> frequent waking without a clear cause</li><li><strong>Delayed sleep pattern:</strong> difficulty sleeping at a consistent time</li><li><strong>Stress-induced wakefulness:</strong> racing thoughts at night</li></ul><h2>Root Causes</h2><p>Anxiety, excessive screen exposure before bed, irregular routines, and unresolved emotional stress are among the most common contributors to disturbed sleep.</p><h2>A Gentle, Individualised Approach</h2><p>Homeopathic treatment for sleep issues considers a person''s mental state, daily habits, and physical symptoms together, aiming to calm the nervous system naturally rather than relying on sedation.</p><h2>Simple Habits That Help</h2><ul><li>A consistent sleep and wake time, even on weekends</li><li>Reducing screens at least 30–45 minutes before bed</li><li>Light stretching or breathing exercises in the evening</li><li>Limiting caffeine after early afternoon</li></ul><p>If poor sleep persists beyond a few weeks, it is worth consulting a professional to address the underlying cause.</p>',
'https://picsum.photos/seed/sleep-disorders/900/600',
'common-issues', true, now() - interval '18 days'),

('The Mind-Body Connection: The Science Behind Homeopathic Healing',
'mind-body-connection-science-behind-homeopathic-healing',
'Emotional and physical health are deeply intertwined. Here is how homeopathy approaches healing by treating the whole person, not just the symptom.',
'<h2>More Than Just Physical Symptoms</h2><p>Modern research increasingly confirms what holistic medicine has long emphasised — chronic stress and unresolved emotions can manifest as physical illness, from digestive issues to skin conditions and chronic fatigue.</p><h2>The Whole-Person Philosophy</h2><p>Homeopathy is built on the principle of treating the individual, not just the disease. A practitioner considers emotional history, personality, lifestyle, and physical symptoms together when selecting a remedy.</p><h2>Why This Matters</h2><p>Two people with the same diagnosis may have very different emotional triggers and constitutions — and therefore respond differently to the same treatment. Individualised care aims to address the root imbalance rather than only the surface symptom.</p><h2>Supporting Long-Term Wellness</h2><ul><li>Reduced recurrence when the underlying cause is addressed</li><li>Gentle action with minimal side effects</li><li>Suitable for long-term, chronic conditions</li><li>Complements lifestyle and emotional wellness practices</li></ul><h2>A Collaborative Path to Healing</h2><p>The mind-body connection is not just a concept — it is the foundation of sustainable healing. Addressing both together often leads to more complete and lasting recovery.</p>',
'https://picsum.photos/seed/mind-body/900/600',
'homeopathy', true, now() - interval '16 days'),

('Managing Panic Attacks: A Step-by-Step Guide',
'managing-panic-attacks-step-by-step-guide',
'Panic attacks can feel terrifying and sudden. Here is a practical guide to understanding them and managing an episode in the moment.',
'<h2>What Happens During a Panic Attack</h2><p>A panic attack is a sudden surge of intense fear accompanied by physical symptoms like a racing heart, shortness of breath, dizziness, or a feeling of losing control — even when there is no real danger present.</p><h2>In-the-Moment Steps</h2><ul><li><strong>Ground yourself:</strong> name 5 things you can see, 4 you can touch, 3 you can hear</li><li><strong>Slow your breath:</strong> inhale for 4 counts, hold for 4, exhale for 6</li><li><strong>Remind yourself:</strong> "This is panic, it will pass, I am safe"</li><li><strong>Avoid fighting it:</strong> resisting the sensations often intensifies them</li></ul><h2>After an Episode</h2><p>Rest, hydrate, and avoid judging yourself. Panic attacks are exhausting but not dangerous on their own.</p><h2>Long-Term Management</h2><p>Recurrent panic attacks benefit from a combined approach — understanding personal triggers, lifestyle adjustments, and individualised treatment that addresses the underlying anxiety pattern rather than just the acute episode.</p><h2>When to Seek Help</h2><p>If panic attacks are frequent or affecting your daily functioning, professional guidance can help you build long-term coping strategies and address root causes.</p>',
'https://picsum.photos/seed/panic-attacks/900/600',
'anxiety-stress', true, now() - interval '14 days'),

('Building Healthy Relationships Through Better Communication',
'building-healthy-relationships-through-better-communication',
'Most relationship conflicts stem from communication breakdowns, not incompatibility. Here is how to build stronger, healthier connections.',
'<h2>Why Communication Breaks Down</h2><p>Miscommunication often happens not because of what is said, but how and when it is said — during stress, without listening, or with assumptions instead of clarity.</p><h2>Habits of Healthy Communicators</h2><ul><li>Listening to understand, not just to respond</li><li>Using "I feel" statements instead of blame</li><li>Taking a pause during heated moments before responding</li><li>Being specific about needs instead of expecting mind-reading</li></ul><h2>Repairing After Conflict</h2><p>Healthy relationships are not conflict-free — they are repair-capable. Acknowledging mistakes, validating each other''s feelings, and returning to calm conversation are what make relationships resilient over time.</p><h2>When Old Patterns Resurface</h2><p>Sometimes repeated conflict points to deeper, unresolved emotional patterns from earlier relationships or experiences. Recognising this can shift blame into understanding.</p><h2>Seeking Support</h2><p>Couples or individual counselling is not a sign of failure — it is a proactive step toward building the relationship skills that were never formally taught to most of us.</p>',
'https://picsum.photos/seed/relationships-communication/900/600',
'relationships', true, now() - interval '12 days'),

('Teenage Mental Health: What Parents Need to Know',
'teenage-mental-health-what-parents-need-to-know',
'Adolescence brings rapid emotional change. Here is how parents can recognise warning signs and support their teen''s mental wellbeing.',
'<h2>Why Teen Years Are Different</h2><p>The adolescent brain is undergoing major development in emotional regulation and decision-making, making teens more vulnerable to mood swings, anxiety, and social pressure than either children or adults.</p><h2>Warning Signs to Watch For</h2><ul><li>Withdrawal from friends or family</li><li>Sudden drop in academic performance</li><li>Changes in sleep or appetite</li><li>Increased irritability or secrecy</li><li>Excessive use of social media paired with mood changes</li></ul><h2>How Parents Can Help</h2><p>Creating a judgment-free space for open conversation is often more effective than direct confrontation. Teens are more likely to open up when they feel heard rather than lectured.</p><h2>Balancing Independence and Support</h2><p>Teenagers need growing independence, but also the reassurance that support is available without conditions. Checking in regularly, without being intrusive, builds trust over time.</p><h2>When to Involve a Professional</h2><p>If warning signs persist for more than two weeks or involve any mention of self-harm, seeking professional support immediately is essential — early intervention makes a significant difference at this age.</p>',
'https://picsum.photos/seed/teen-mental-health/900/600',
'parenting', true, now() - interval '10 days'),

('Work Stress and Burnout: A Rising Concern Among Young Professionals',
'work-stress-burnout-rising-concern-young-professionals',
'Burnout is becoming one of the most talked-about workplace issues today. Here is how to recognise it early and protect your mental health.',
'<h2>What Is Burnout?</h2><p>Burnout is a state of chronic physical and emotional exhaustion caused by prolonged workplace stress, marked by cynicism, reduced performance, and a sense of detachment from work that once felt meaningful.</p><h2>Why It Is Rising</h2><ul><li>Always-on work culture and blurred boundaries with remote work</li><li>Constant digital notifications and reduced downtime</li><li>High competition and job insecurity</li><li>Lack of institutional support for mental wellbeing</li></ul><h2>Early Warning Signs</h2><p>Persistent fatigue even after rest, dreading work, reduced productivity despite longer hours, and increased cynicism toward colleagues or tasks are all early indicators.</p><h2>Protecting Yourself</h2><ul><li>Set clear boundaries around work hours</li><li>Take real breaks — away from screens</li><li>Talk openly with a manager or mentor about workload</li><li>Prioritise sleep and physical movement</li></ul><h2>When Rest Is Not Enough</h2><p>If burnout persists despite time off, it may have progressed into clinical anxiety or depression, which benefits from professional support rather than self-management alone.</p>',
'https://picsum.photos/seed/work-burnout/900/600',
'trending', true, now() - interval '8 days'),

('OCD Explained: Symptoms, Myths, and Treatment Options',
'ocd-explained-symptoms-myths-treatment-options',
'Obsessive-Compulsive Disorder is widely misunderstood. Here is what it actually looks like — and how it can be effectively managed.',
'<h2>What OCD Really Is</h2><p>OCD involves intrusive, unwanted thoughts (obsessions) and repetitive behaviours or mental acts (compulsions) performed to reduce the distress those thoughts cause. It is far more disruptive than casual "neatness" or preference for order.</p><h2>Common Myths</h2><ul><li><strong>Myth:</strong> OCD is just about cleanliness. <strong>Fact:</strong> obsessions can involve harm, doubt, symmetry, or unwanted thoughts of any kind.</li><li><strong>Myth:</strong> People with OCD enjoy their rituals. <strong>Fact:</strong> compulsions are driven by anxiety relief, not pleasure.</li><li><strong>Myth:</strong> It is rare. <strong>Fact:</strong> OCD affects a meaningful percentage of the population, often undiagnosed for years.</li></ul><h2>How It Affects Daily Life</h2><p>Excessive checking, repeated reassurance-seeking, or rigid routines can consume hours each day, impacting work, relationships, and self-esteem.</p><h2>A Path Toward Management</h2><p>Individualised treatment that addresses the person''s specific triggers and anxiety patterns, combined with gradual behavioural strategies, can significantly reduce the frequency and intensity of OCD symptoms over time.</p><h2>Reducing Stigma</h2><p>OCD is a genuine, treatable condition — not a personality quirk. Understanding this helps both patients and families approach it with the compassion it deserves.</p>',
'https://picsum.photos/seed/ocd-explained/900/600',
'common-issues', true, now() - interval '6 days'),

('Homeopathy for Women''s Hormonal and Emotional Balance',
'homeopathy-womens-hormonal-emotional-balance',
'Hormonal shifts affect far more than the body — they influence mood, energy, and emotional resilience. Here is how homeopathy supports women through these changes.',
'<h2>The Hormone-Emotion Link</h2><p>From puberty to menopause, hormonal fluctuations can significantly affect mood, sleep, and emotional stability — often showing up as irritability, anxiety, or unexplained fatigue.</p><h2>Common Concerns Women Face</h2><ul><li>PMS-related mood swings and irritability</li><li>Postpartum emotional changes</li><li>Perimenopause and menopause-related anxiety or low mood</li><li>Stress-related menstrual irregularities</li></ul><h2>Why Individualised Care Matters</h2><p>Two women experiencing similar hormonal changes may have very different emotional responses. Homeopathic treatment considers each woman''s unique constitution, symptoms, and emotional pattern rather than applying a single standard protocol.</p><h2>A Gentle, Long-Term Approach</h2><p>Rather than only masking symptoms during difficult weeks, the goal is to support the body''s natural hormonal and emotional balance over time, with minimal side effects.</p><h2>Supporting Yourself Alongside Treatment</h2><ul><li>Regular movement and adequate rest</li><li>Balanced nutrition through hormonal transitions</li><li>Open conversations with family about mood changes</li><li>Tracking patterns to identify personal triggers</li></ul><p>If hormonal changes are significantly affecting your quality of life, individualised professional care can make a meaningful difference.</p>',
'https://picsum.photos/seed/womens-hormonal-balance/900/600',
'homeopathy', true, now() - interval '4 days'),

('Overcoming Social Anxiety in a Digital Age',
'overcoming-social-anxiety-in-digital-age',
'Ironically, in an age of constant connectivity, social anxiety is on the rise. Here is why — and how to gradually build confidence in real-world interactions.',
'<h2>A Growing, Modern Concern</h2><p>Social anxiety involves an intense fear of judgment in social situations. In recent years, increased reliance on digital communication has made many people — especially younger generations — less practiced at face-to-face interaction.</p><h2>How Digital Life Contributes</h2><ul><li>Curated social media creates unrealistic comparison</li><li>Text-based communication reduces practice with real-time social cues</li><li>Fear of judgment is amplified by public online feedback (likes, comments)</li><li>Avoidance becomes easier with virtual alternatives to in-person contact</li></ul><h2>Signs of Social Anxiety</h2><p>Avoiding gatherings, intense fear before social events, overanalysing past interactions, and physical symptoms like sweating or trembling in social settings are common indicators.</p><h2>Building Confidence Gradually</h2><ul><li>Start with low-pressure interactions and build up gradually</li><li>Challenge catastrophic assumptions about others'' judgments</li><li>Limit social media comparison, especially before social events</li><li>Practice self-compassion after imperfect interactions</li></ul><h2>Professional Support Helps</h2><p>For persistent social anxiety, individualised therapeutic and homeopathic support can help address both the emotional root and day-to-day coping strategies.</p>',
'https://picsum.photos/seed/social-anxiety/900/600',
'trending', true, now() - interval '2 days'),

('Grief and Loss: Finding a Path to Emotional Healing',
'grief-and-loss-finding-path-to-emotional-healing',
'Grief is one of the most profound emotional experiences we face. Here is a compassionate look at the healing process — and how to support yourself or a loved one through it.',
'<h2>Grief Is Not Linear</h2><p>Unlike the commonly cited "five stages," grief rarely moves in a straight line. Waves of sadness, anger, guilt, or even relief can resurface unexpectedly, long after a loss.</p><h2>Common Experiences During Grief</h2><ul><li>Difficulty concentrating or sleeping</li><li>Physical exhaustion and reduced appetite</li><li>Guilt over moments of normalcy or forgetting, briefly, to grieve</li><li>Isolation, even from well-meaning support</li></ul><h2>Supporting Yourself Through Grief</h2><ul><li>Allow yourself to feel emotions without a timeline</li><li>Maintain basic routines like sleep and meals where possible</li><li>Talk about your loss rather than suppressing it</li><li>Seek support from those who allow space for your process, not rush it</li></ul><h2>When Grief Becomes Complicated</h2><p>If grief persists intensely for many months without any easing, or significantly disrupts daily functioning, it may have developed into complicated grief — which benefits from professional, compassionate support.</p><h2>A Gentle Reminder</h2><p>Healing does not mean forgetting. It means learning to carry the loss with less overwhelming pain over time — and it is entirely acceptable to ask for help along the way.</p>',
'https://picsum.photos/seed/grief-healing/900/600',
'mental-health', true, now() - interval '1 days')

on conflict (slug) do nothing;
