-- ============================================================
-- Blog EXPANSION Script — Mind Motion Matrix (Dr. Kirthi Kakade)
-- Run this AFTER the first seed script, in Supabase SQL Editor.
-- Updates all 15 existing posts with deeper, longer content
-- (separate "Reason" and "Solution" sections) + adds 2 new
-- posts on homeopathy's supportive role alongside cancer/oncology care.
-- Safe to re-run.
-- ============================================================

update blog_posts set content = '<h2>What Is Anxiety?</h2><p>Anxiety is the body''s natural alarm system, designed to protect us from danger. But when this alarm keeps ringing even in safe, everyday situations, it becomes an anxiety disorder — one of the most common mental health concerns in India today, affecting students, working professionals, and homemakers alike.</p><h2>Signs You Should Not Ignore</h2><ul><li>Constant overthinking or catastrophic "what if" thoughts</li><li>Racing heartbeat, sweating, or shortness of breath without physical cause</li><li>Trouble concentrating, remembering things, or falling asleep</li><li>Irritability, restlessness, or muscle tension</li><li>Avoiding social situations, travel, or responsibilities out of fear</li></ul><h2>Reason: Why Anxiety Develops</h2><p>Anxiety rarely has a single cause. It usually builds from a combination of factors:</p><ul><li><strong>Genetics and temperament:</strong> a naturally sensitive nervous system inherited from family</li><li><strong>Prolonged stress:</strong> academic pressure, job insecurity, financial strain, or relationship conflict</li><li><strong>Unresolved trauma:</strong> past experiences the mind has not fully processed</li><li><strong>Hormonal changes:</strong> puberty, pregnancy, postpartum, or thyroid imbalance</li><li><strong>Lifestyle factors:</strong> poor sleep, excessive caffeine, and constant screen stimulation keeping the nervous system "switched on"</li></ul><p>Understanding the specific reason behind your anxiety is important — generic advice rarely works because everyone''s triggers are different.</p><h2>Solution: A Homeopathic and Lifestyle Approach</h2><p>Homeopathy approaches anxiety by treating the person as a whole, not just the symptom. A detailed case history — including personality, fears, sleep pattern, and physical symptoms — helps select an individualised remedy aimed at calming the nervous system gradually, without the dependency risk associated with some conventional sedatives.</p><p>Alongside treatment, these daily habits support recovery:</p><ul><li>A fixed wake-up and sleep time, even on weekends</li><li>10-15 minutes of daily breathing exercises or meditation</li><li>Reducing caffeine and late-night screen use</li><li>Talking openly with a trusted person instead of bottling up worry</li></ul><h2>When to Seek Professional Help</h2><p>If anxiety is affecting your work, relationships, or sleep for more than a few weeks, it is time to consult a qualified professional. Anxiety is highly manageable — the earlier you seek support, the smoother the recovery.</p>'
where slug = 'understanding-anxiety-signs-causes-homeopathic-approach';

update blog_posts set content = '<h2>Depression Is Not Just "Feeling Low"</h2><p>Chronic depression is a persistent state — lasting weeks or months — marked by loss of interest, low energy, disturbed sleep, and a sense of hopelessness that does not lift on its own. It affects people across every age and background, though it often goes unspoken due to stigma.</p><h2>Reason: What Causes Depression to Take Hold</h2><ul><li><strong>Biochemical imbalance:</strong> disruptions in brain chemicals that regulate mood</li><li><strong>Unresolved grief or loss:</strong> emotional pain that was never fully processed</li><li><strong>Chronic, ongoing stress:</strong> work pressure, financial strain, or caregiving fatigue</li><li><strong>Hormonal shifts:</strong> postpartum changes, thyroid issues, or perimenopause</li><li><strong>Genetic predisposition:</strong> a family history of depression or anxiety</li></ul><p>In most cases, depression develops slowly and is initially dismissed as "just a phase" until it becomes overwhelming — which is why early recognition matters.</p><h2>Solution: A Constitutional, Whole-Person Approach</h2><p>Rather than a one-size-fits-all remedy, homeopathic treatment for depression is individualised. It considers a person''s emotional triggers, physical constitution, sleep pattern, and personal history together, aiming to address the underlying imbalance rather than only masking symptoms.</p><p>Supportive daily practices that work alongside treatment include:</p><ul><li>Regular sunlight exposure and gentle movement or walking</li><li>A consistent sleep-wake schedule</li><li>Reducing isolation through supportive relationships and conversation</li><li>Mindful reduction of stimulants like caffeine, especially later in the day</li></ul><h2>Recovery Is Gradual — and Real</h2><p>With consistent, individualised care, many patients experience a steady return of energy, motivation, and emotional stability over weeks and months. If you or a loved one is struggling, reaching out for professional support is the most important first step — you do not have to manage it alone.</p>'
where slug = 'how-homeopathy-treats-chronic-depression-naturally';

update blog_posts set content = '<h2>Why Early Detection Matters</h2><p>Chronic, unmanaged stress is linked to anxiety, poor sleep, digestive issues, and a weakened immune system. Recognising it early — before it becomes overwhelming — makes it far easier to manage.</p><h2>Reason: Why These Signs Appear</h2><p>Stress triggers a surge of cortisol and adrenaline meant for short bursts of "fight or flight." When stress becomes constant, these hormones stay elevated, disrupting sleep, digestion, mood, and muscle tension. Here are five signals your body may be sending:</p><ul><li><strong>Persistent fatigue:</strong> tiredness even after a full night''s sleep, caused by prolonged cortisol exposure</li><li><strong>Irritability over small things:</strong> an overloaded nervous system reacting disproportionately to minor triggers</li><li><strong>Changes in appetite:</strong> stress hormones can suppress or spike hunger, leading to skipped meals or emotional eating</li><li><strong>Difficulty sleeping:</strong> racing thoughts at bedtime or frequent waking from an overactive mind</li><li><strong>Physical tension:</strong> unexplained headaches, jaw clenching, or tight shoulders from constant muscular bracing</li></ul><h2>Solution: Practical Steps to Reduce Stress</h2><ul><li>Short daily walks, ideally outdoors and away from screens</li><li>Deep breathing: 4 seconds in, 4 seconds hold, 6 seconds out, repeated for a few minutes</li><li>A short digital detox window each evening before bed</li><li>Speaking to someone you trust rather than carrying it silently</li><li>Individualised homeopathic support, which can gently ease the nervous system''s overactivity over time</li></ul><h2>When It Is Time for Professional Support</h2><p>If these signs persist for several weeks despite lifestyle changes, consider speaking with a professional — chronic stress is very treatable with the right, personalised approach.</p>'
where slug = '5-early-signs-of-stress-you-should-not-ignore';

update blog_posts set content = '<h2>Understanding ADHD in Children</h2><p>Attention-Deficit/Hyperactivity Disorder affects a child''s ability to focus, sit still, and regulate impulses. It is not a result of poor parenting — it is a neurodevelopmental pattern that benefits from structured support, patience, and the right treatment approach.</p><h2>Common Signs Parents Notice</h2><ul><li>Difficulty completing homework or multi-step tasks</li><li>Constant fidgeting, restlessness, or difficulty sitting through meals or class</li><li>Interrupting conversations or struggling to wait their turn</li><li>Emotional outbursts that seem sudden and intense</li></ul><h2>Reason: Why ADHD Happens</h2><p>ADHD is linked to differences in brain development, particularly in areas that regulate attention and impulse control. Genetics play a significant role, and factors like early developmental history, sleep quality, and screen exposure can influence how symptoms present, though they are not the root cause.</p><h2>Solution: Supporting Your Child at Home and Through Treatment</h2><p>Creating a supportive environment makes a real difference:</p><ul><li>Consistent daily routines with clear, simple instructions</li><li>Positive reinforcement for small wins, rather than focusing only on mistakes</li><li>Adequate physical activity to channel excess energy constructively</li><li>Breaking tasks into smaller, manageable steps</li></ul><p>Homeopathic treatment for ADHD focuses on the child''s individual temperament, sleep pattern, and behavioural triggers, aiming to support calmer focus and emotional regulation gently — without the sedative effects some parents worry about with conventional medication.</p><h2>Working With Professionals</h2><p>A collaborative approach involving parents, teachers, and your treating doctor gives children with ADHD the best chance to thrive academically, socially, and emotionally. Regular follow-ups help fine-tune the approach as your child grows.</p>'
where slug = 'parenting-child-with-adhd-homeopathic-perspective';

update blog_posts set content = '<h2>A Growing but Silent Crisis</h2><p>Surveys consistently show a significant proportion of Indians experience mental health concerns at some point, yet a majority never seek professional help due to stigma, lack of awareness, or limited access to affordable care.</p><h2>Reason: Why the Stigma Persists</h2><ul><li>Mental health struggles are often dismissed as "weakness" or a lack of willpower</li><li>Fear of judgment from family, colleagues, or community</li><li>Limited mental health education in schools and workplaces</li><li>Confusion between normal sadness and clinical conditions requiring treatment</li></ul><p>This silence delays treatment and worsens outcomes for people who could otherwise recover well with timely, professional care.</p><h2>Solution: What Is Changing — and What Helps</h2><ul><li>Workplaces introducing mental health days and counselling access</li><li>Schools starting emotional wellness and life-skills programs</li><li>Public figures speaking openly about their own mental health struggles</li><li>Growing acceptance of therapy and holistic treatment options, including homeopathy, as legitimate paths to wellbeing</li></ul><h2>What You Can Do</h2><p>Start conversations at home and at work. Check in on people around you without judgment. Encourage — rather than discourage — someone who wants to seek help. Awareness saves lives, and it starts with each of us choosing to speak openly.</p>'
where slug = 'why-mental-health-awareness-matters-in-india-today';

update blog_posts set content = '<h2>Why Sleep Matters So Much</h2><p>Sleep is when the brain consolidates memory, regulates emotion, and the body repairs itself. Chronic poor sleep is linked to anxiety, weight gain, weakened immunity, and reduced concentration during the day.</p><h2>Common Sleep Disorders</h2><ul><li><strong>Insomnia:</strong> difficulty falling or staying asleep</li><li><strong>Restless sleep:</strong> frequent waking without a clear cause</li><li><strong>Delayed sleep pattern:</strong> difficulty sleeping at a consistent, healthy time</li><li><strong>Stress-induced wakefulness:</strong> racing thoughts that keep the mind active at night</li></ul><h2>Reason: What Disrupts Sleep</h2><p>Anxiety, excessive screen exposure before bed, irregular routines, and unresolved emotional stress are among the most common contributors to disturbed sleep. Blue light from phones suppresses melatonin, while an overactive, worried mind keeps the nervous system alert well past bedtime.</p><h2>Solution: A Gentle, Individualised Approach</h2><p>Homeopathic treatment for sleep issues considers a person''s mental state, daily habits, and physical symptoms together, aiming to calm the nervous system naturally rather than relying on sedation. This can be especially helpful for people who feel "wired but tired."</p><p>Simple habits that support better sleep:</p><ul><li>A consistent sleep and wake time, even on weekends</li><li>Reducing screens at least 30-45 minutes before bed</li><li>Light stretching or breathing exercises in the evening</li><li>Limiting caffeine intake after early afternoon</li></ul><h2>When to Seek Help</h2><p>If poor sleep persists beyond a few weeks and affects your daytime functioning, it is worth consulting a professional to identify and address the underlying cause rather than relying on short-term fixes.</p>'
where slug = 'common-sleep-disorders-how-homeopathy-can-help';

update blog_posts set content = '<h2>More Than Just Physical Symptoms</h2><p>Modern research increasingly confirms what holistic medicine has long emphasised — chronic stress and unresolved emotions can manifest as physical illness, from digestive issues to skin conditions and chronic fatigue.</p><h2>Reason: Why Emotions Affect the Body</h2><p>The nervous, hormonal, and immune systems are deeply interconnected. Prolonged emotional stress keeps the body in a heightened alert state, which over time can disrupt digestion, sleep, skin health, and hormonal balance — even when there is no obvious physical illness present.</p><h2>The Whole-Person Philosophy of Homeopathy</h2><p>Homeopathy is built on the principle of treating the individual, not just the disease. A practitioner considers emotional history, personality, lifestyle, and physical symptoms together when selecting a remedy — recognising that two people with the same diagnosis may have very different emotional triggers and constitutions.</p><h2>Solution: An Individualised, Long-Term Approach</h2><ul><li>Reduced recurrence when the underlying emotional cause is also addressed</li><li>Gentle action with minimal side effects, suitable for long-term, chronic conditions</li><li>Complements lifestyle changes and emotional wellness practices like therapy or mindfulness</li><li>Focuses on restoring balance rather than only suppressing symptoms temporarily</li></ul><h2>A Collaborative Path to Healing</h2><p>The mind-body connection is not just a concept — it is the foundation of sustainable healing. Addressing both physical symptoms and their emotional roots together often leads to more complete and lasting recovery.</p>'
where slug = 'mind-body-connection-science-behind-homeopathic-healing';

update blog_posts set content = '<h2>What Happens During a Panic Attack</h2><p>A panic attack is a sudden surge of intense fear accompanied by physical symptoms like a racing heart, shortness of breath, dizziness, or a feeling of losing control — even when there is no real danger present. It typically peaks within minutes but can feel terrifying while it lasts.</p><h2>Reason: Why Panic Attacks Happen</h2><p>Panic attacks occur when the body''s fight-or-flight response activates without an actual external threat, often triggered by accumulated stress, underlying anxiety disorders, or even specific memories and associations. Once a person fears having another attack, this fear itself can become a trigger, creating a cycle.</p><h2>Solution: In-the-Moment Steps</h2><ul><li><strong>Ground yourself:</strong> name 5 things you can see, 4 you can touch, 3 you can hear</li><li><strong>Slow your breath:</strong> inhale for 4 counts, hold for 4, exhale for 6</li><li><strong>Remind yourself:</strong> "This is panic, it will pass, I am safe"</li><li><strong>Avoid fighting it:</strong> resisting the sensations often intensifies them; allowing them to pass is more effective</li></ul><h2>After an Episode</h2><p>Rest, hydrate, and avoid judging yourself. Panic attacks are exhausting but not dangerous on their own.</p><h2>Solution: Long-Term Management</h2><p>Recurrent panic attacks benefit from a combined approach — understanding personal triggers, gradual lifestyle adjustments, and individualised homeopathic treatment that addresses the underlying anxiety pattern rather than just the acute episode.</p><h2>When to Seek Help</h2><p>If panic attacks are frequent or affecting your daily functioning, professional guidance can help you build long-term coping strategies and address root causes rather than just managing individual episodes.</p>'
where slug = 'managing-panic-attacks-step-by-step-guide';

update blog_posts set content = '<h2>Why Communication Breaks Down</h2><p>Miscommunication often happens not because of what is said, but how and when it is said — during stress, without listening, or with assumptions instead of clarity.</p><h2>Reason: Common Root Causes</h2><ul><li>Speaking during emotional flare-ups rather than pausing first</li><li>Assuming the other person should "just know" what we need</li><li>Listening only to respond or defend, rather than to understand</li><li>Carrying unresolved patterns from past relationships or upbringing into current ones</li></ul><h2>Solution: Habits of Healthy Communicators</h2><ul><li>Listening to understand, not just to respond</li><li>Using "I feel" statements instead of blame ("I feel unheard" instead of "You never listen")</li><li>Taking a pause during heated moments before responding</li><li>Being specific about needs instead of expecting mind-reading</li></ul><h2>Repairing After Conflict</h2><p>Healthy relationships are not conflict-free — they are repair-capable. Acknowledging mistakes, validating each other''s feelings, and returning to calm conversation are what make relationships resilient over time.</p><h2>When Old Patterns Resurface</h2><p>Sometimes repeated conflict points to deeper, unresolved emotional patterns from earlier relationships or experiences. Recognising this can shift blame into understanding, and often benefits from outside perspective.</p><h2>Seeking Support</h2><p>Couples or individual counselling is not a sign of failure — it is a proactive step toward building the relationship skills that were never formally taught to most of us.</p>'
where slug = 'building-healthy-relationships-through-better-communication';

update blog_posts set content = '<h2>Why Teen Years Are Different</h2><p>The adolescent brain is undergoing major development in emotional regulation and decision-making, making teens more vulnerable to mood swings, anxiety, and social pressure than either children or adults.</p><h2>Reason: What Drives These Changes</h2><ul><li>Rapid hormonal shifts affecting mood and energy</li><li>Increased social comparison, amplified by social media</li><li>Academic and peer pressure intensifying during these years</li><li>A still-developing prefrontal cortex, which affects impulse control and long-term thinking</li></ul><h2>Warning Signs to Watch For</h2><ul><li>Withdrawal from friends or family</li><li>Sudden drop in academic performance</li><li>Changes in sleep or appetite</li><li>Increased irritability or secrecy</li><li>Excessive use of social media paired with mood changes</li></ul><h2>Solution: How Parents Can Help</h2><p>Creating a judgment-free space for open conversation is often more effective than direct confrontation. Teens are more likely to open up when they feel heard rather than lectured.</p><ul><li>Check in regularly without being intrusive</li><li>Avoid dismissing feelings as "just a phase"</li><li>Model healthy stress management yourself</li><li>Balance independence with reassurance that support is unconditional</li></ul><h2>When to Involve a Professional</h2><p>If warning signs persist for more than two weeks or involve any mention of self-harm, seeking professional support immediately is essential — early intervention makes a significant difference at this age.</p>'
where slug = 'teenage-mental-health-what-parents-need-to-know';

update blog_posts set content = '<h2>What Is Burnout?</h2><p>Burnout is a state of chronic physical and emotional exhaustion caused by prolonged workplace stress, marked by cynicism, reduced performance, and a sense of detachment from work that once felt meaningful.</p><h2>Reason: Why It Is Rising</h2><ul><li>Always-on work culture and blurred boundaries with remote work</li><li>Constant digital notifications and reduced genuine downtime</li><li>High competition and job insecurity, especially among younger professionals</li><li>Lack of institutional support for mental wellbeing at many workplaces</li></ul><h2>Early Warning Signs</h2><p>Persistent fatigue even after rest, dreading work, reduced productivity despite longer hours, and increased cynicism toward colleagues or tasks are all early indicators worth taking seriously.</p><h2>Solution: Protecting Yourself</h2><ul><li>Set clear boundaries around work hours, including notification-free time</li><li>Take real breaks — away from screens, ideally outdoors</li><li>Talk openly with a manager or mentor about workload before it becomes unmanageable</li><li>Prioritise sleep and physical movement as non-negotiables, not luxuries</li></ul><h2>When Rest Is Not Enough</h2><p>If burnout persists despite time off, it may have progressed into clinical anxiety or depression, which benefits from professional, individualised support rather than self-management alone. Recognising this shift early prevents longer-term impact on both career and health.</p>'
where slug = 'work-stress-burnout-rising-concern-young-professionals';

update blog_posts set content = '<h2>What OCD Really Is</h2><p>OCD involves intrusive, unwanted thoughts (obsessions) and repetitive behaviours or mental acts (compulsions) performed to reduce the distress those thoughts cause. It is far more disruptive than casual "neatness" or a preference for order.</p><h2>Common Myths</h2><ul><li><strong>Myth:</strong> OCD is just about cleanliness. <strong>Fact:</strong> obsessions can involve harm, doubt, symmetry, or unwanted thoughts of any kind.</li><li><strong>Myth:</strong> People with OCD enjoy their rituals. <strong>Fact:</strong> compulsions are driven by anxiety relief, not pleasure.</li><li><strong>Myth:</strong> It is rare. <strong>Fact:</strong> OCD affects a meaningful percentage of the population, often undiagnosed for years.</li></ul><h2>Reason: Why OCD Develops</h2><p>OCD is linked to a combination of genetic predisposition, differences in brain circuitry involved in threat detection, and environmental triggers such as major stress or trauma. It is a medical condition, not a personal failing or lack of discipline.</p><h2>How It Affects Daily Life</h2><p>Excessive checking, repeated reassurance-seeking, or rigid routines can consume hours each day, impacting work, relationships, and self-esteem.</p><h2>Solution: A Path Toward Management</h2><p>Individualised treatment that addresses the person''s specific triggers and anxiety patterns, combined with gradual behavioural strategies, can significantly reduce the frequency and intensity of OCD symptoms over time. Homeopathic care, tailored to the person''s full emotional and physical picture, can support this process gently alongside behavioural approaches.</p><h2>Reducing Stigma</h2><p>OCD is a genuine, treatable condition — not a personality quirk. Understanding this helps both patients and families approach it with the compassion it deserves.</p>'
where slug = 'ocd-explained-symptoms-myths-treatment-options';

update blog_posts set content = '<h2>The Hormone-Emotion Link</h2><p>From puberty to menopause, hormonal fluctuations can significantly affect mood, sleep, and emotional stability — often showing up as irritability, anxiety, or unexplained fatigue that women may not immediately connect to their hormonal cycle.</p><h2>Common Concerns Women Face</h2><ul><li>PMS-related mood swings and irritability</li><li>Postpartum emotional changes and adjustment</li><li>Perimenopause and menopause-related anxiety or low mood</li><li>Stress-related menstrual irregularities</li></ul><h2>Reason: Why Individualised Care Matters</h2><p>Two women experiencing similar hormonal changes may have very different emotional responses, shaped by their overall constitution, life circumstances, and stress levels. A standard, one-size-fits-all protocol often misses this nuance.</p><h2>Solution: A Gentle, Long-Term Approach</h2><p>Homeopathic treatment considers each woman''s unique constitution, symptoms, and emotional pattern rather than applying a single standard protocol. Rather than only masking symptoms during difficult weeks, the goal is to support the body''s natural hormonal and emotional balance over time, with minimal side effects.</p><h2>Supporting Yourself Alongside Treatment</h2><ul><li>Regular movement and adequate rest</li><li>Balanced nutrition through hormonal transitions</li><li>Open conversations with family about mood changes</li><li>Tracking patterns to identify personal triggers over time</li></ul><p>If hormonal changes are significantly affecting your quality of life, individualised professional care can make a meaningful difference.</p>'
where slug = 'homeopathy-womens-hormonal-emotional-balance';

update blog_posts set content = '<h2>A Growing, Modern Concern</h2><p>Social anxiety involves an intense fear of judgment in social situations. In recent years, increased reliance on digital communication has made many people — especially younger generations — less practiced at face-to-face interaction.</p><h2>Reason: How Digital Life Contributes</h2><ul><li>Curated social media creates unrealistic comparison with others'' highlight reels</li><li>Text-based communication reduces practice with real-time social cues like tone and body language</li><li>Fear of judgment is amplified by public online feedback such as likes and comments</li><li>Avoidance becomes easier with virtual alternatives to in-person contact</li></ul><h2>Signs of Social Anxiety</h2><p>Avoiding gatherings, intense fear before social events, overanalysing past interactions, and physical symptoms like sweating or trembling in social settings are common indicators.</p><h2>Solution: Building Confidence Gradually</h2><ul><li>Start with low-pressure interactions and build up gradually over time</li><li>Challenge catastrophic assumptions about others'' judgments</li><li>Limit social media comparison, especially before social events</li><li>Practice self-compassion after imperfect interactions, rather than harsh self-criticism</li></ul><h2>Professional Support Helps</h2><p>For persistent social anxiety, individualised therapeutic and homeopathic support can help address both the emotional root and day-to-day coping strategies, allowing more comfortable, genuine connection over time.</p>'
where slug = 'overcoming-social-anxiety-in-digital-age';

update blog_posts set content = '<h2>Grief Is Not Linear</h2><p>Unlike the commonly cited "five stages," grief rarely moves in a straight line. Waves of sadness, anger, guilt, or even relief can resurface unexpectedly, long after a loss.</p><h2>Reason: Why Grief Feels So Overwhelming</h2><p>Grief involves the loss of not just a person, but often a sense of routine, identity, and future expectations built around that relationship. The mind and body process this disruption gradually, which is why grief can resurface in waves rather than resolving on a fixed timeline.</p><h2>Common Experiences During Grief</h2><ul><li>Difficulty concentrating or sleeping</li><li>Physical exhaustion and reduced appetite</li><li>Guilt over moments of normalcy or briefly forgetting to grieve</li><li>Isolation, even from well-meaning support</li></ul><h2>Solution: Supporting Yourself Through Grief</h2><ul><li>Allow yourself to feel emotions without imposing a timeline</li><li>Maintain basic routines like sleep and meals where possible</li><li>Talk about your loss rather than suppressing it</li><li>Seek support from those who allow space for your process, rather than rushing it</li></ul><h2>When Grief Becomes Complicated</h2><p>If grief persists intensely for many months without any easing, or significantly disrupts daily functioning, it may have developed into complicated grief — which benefits from professional, compassionate support.</p><h2>A Gentle Reminder</h2><p>Healing does not mean forgetting. It means learning to carry the loss with less overwhelming pain over time — and it is entirely acceptable to ask for help along the way.</p>'
where slug = 'grief-and-loss-finding-path-to-emotional-healing';

-- ============================================================
-- NEW: 2 posts on homeopathy''s SUPPORTIVE role alongside cancer
-- care. These are written carefully as complementary/emotional
-- support content — NOT as claims that homeopathy cures or
-- replaces oncology treatment. Conventional cancer treatment is
-- always presented as the primary, necessary care.
-- ============================================================

insert into blog_posts (title, slug, excerpt, content, cover_image, category, published, published_at) values

('Coping Emotionally With a Cancer Diagnosis: A Supportive Approach',
'coping-emotionally-with-cancer-diagnosis-supportive-approach',
'A cancer diagnosis brings immense emotional weight for patients and families alike. Here is how emotional and homeopathic support can work alongside oncology treatment to ease this journey.',
'<h2>The Emotional Weight of a Diagnosis</h2><p>A cancer diagnosis affects far more than the body — it brings fear, uncertainty, grief, and disruption to daily life for both patients and their families. Emotional wellbeing during this time is just as important as physical treatment.</p><h2>Reason: Why Emotional Support Is Often Overlooked</h2><p>Cancer care understandably focuses heavily on medical treatment — surgery, chemotherapy, radiation — under the guidance of an oncologist. In this focus, the emotional toll of anxiety, sleeplessness, fear, and caregiver exhaustion can be under-addressed, even though it significantly affects a patient''s quality of life and resilience through treatment.</p><h2>Solution: A Complementary, Whole-Person Approach</h2><p>Homeopathy, used as a <strong>complementary support alongside — never a replacement for — prescribed oncology treatment</strong>, can help address some of the emotional and quality-of-life challenges that accompany a cancer journey, such as:</p><ul><li>Anxiety and fear surrounding diagnosis, treatment, or scans</li><li>Disturbed sleep during and after treatment</li><li>General emotional exhaustion and low mood</li><li>Supporting overall wellbeing alongside medical care</li></ul><p>It is essential that any complementary care is discussed openly with your treating oncologist, so it works in coordination with — and never interferes with — your primary cancer treatment plan.</p><h2>Supporting a Loved One Through Cancer</h2><ul><li>Listen without trying to "fix" every fear they express</li><li>Help maintain small routines that offer a sense of normalcy</li><li>Encourage them to stay connected with their full care team, including emotional and psychological support</li><li>Take care of your own wellbeing too, as caregiver burnout is real and common</li></ul><h2>A Message of Support</h2><p>Facing cancer is one of life''s most difficult journeys. Combining strong oncological care with emotional and complementary support can help patients and families navigate it with greater resilience and comfort.</p>',
'https://picsum.photos/seed/cancer-emotional-support/900/600',
'common-issues', true, now()),

('Understanding Oncology Treatment: What Patients and Families Should Know',
'understanding-oncology-treatment-what-patients-families-should-know',
'Navigating an oncology treatment plan can feel overwhelming. Here is a clear overview of what to expect — and how holistic, emotional support fits alongside medical care.',
'<h2>What Oncology Care Typically Involves</h2><p>Oncology treatment is highly individualised, depending on cancer type, stage, and overall health. It commonly includes some combination of surgery, chemotherapy, radiation therapy, or targeted treatments, all guided by a specialist oncology team.</p><h2>Reason: Why the Journey Feels Overwhelming</h2><ul><li>Multiple appointments, tests, and specialists to coordinate</li><li>Physical side effects of treatment affecting energy and daily routine</li><li>Uncertainty about outcomes, creating ongoing anxiety</li><li>Balancing treatment with work, family, and financial concerns</li></ul><h2>Solution: Building a Well-Rounded Support System</h2><p>Alongside your primary oncology treatment — which should always remain the central, guiding plan from your specialist — a well-rounded support system can ease the journey considerably:</p><ul><li><strong>Medical team:</strong> your oncologist and specialists guiding the core treatment plan</li><li><strong>Emotional support:</strong> counselling or therapy to process fear, grief, or anxiety</li><li><strong>Complementary care:</strong> individualised homeopathic support for general wellbeing, sleep, and emotional resilience, always coordinated with your oncologist</li><li><strong>Community support:</strong> family, friends, or patient support groups who understand the journey</li></ul><h2>Questions Worth Asking Your Care Team</h2><ul><li>What does the recommended treatment plan involve, step by step?</li><li>What side effects should we prepare for, and how can they be managed?</li><li>Is it safe to combine any complementary or supportive care with the current treatment?</li><li>What resources exist for emotional and caregiver support?</li></ul><h2>A Reminder for Patients and Families</h2><p>You do not have to navigate this alone. A strong care team — medical, emotional, and complementary — working together in coordination gives patients the best possible support through every stage of treatment.</p>',
'https://picsum.photos/seed/oncology-treatment-guide/900/600',
'trending', true, now())

on conflict (slug) do nothing;
